#Stage 1: Build
FROM gradle:8.14.3-jdk21 AS builder
COPY --chown=gradle:gradle . /home/gradle/src

WORKDIR /home/gradle/src
COPY --chown=gradle:gradle . /home/gradle/src
RUN chmod +x ./gradlew
RUN ./gradlew nativeCompile --no-daemon --scan

#Stage 2: Create final image with only runtime and the jar
FROM debian:bookworm-slim
WORKDIR /app
#Copy the binary compiled from the builder stage
COPY --from=builder /app/build/native/nativeCompile /app/my-app

EXPOSE 8080
ENTRYPOINT ["/app/my-app"]