#Stage 1: Build
FROM ghcr.io/graalvm/native-image-community:21 AS builder
RUN microdnf install findutils -y

WORKDIR /app
COPY --chown=graalvm:graalvm . /app
RUN chmod +x ./gradlew
RUN ./gradlew nativeCompile --no-daemon --scan

#Stage 2: Create final image with only runtime and the jar
FROM debian:bookworm-slim
WORKDIR /app
#Copy the binary compiled from the builder stage
COPY --from=builder /app/build/native/nativeCompile /app/my-app

EXPOSE 8080
ENTRYPOINT ["/app/my-app"]